# Comment out certain settings to use default values.
# For more settings, please refer to the documentation:
# https://bytecodealliance.github.io/wasmtime/cli-cache.html

[cache]
enabled = true
directory = "/tmp/wasmtime-cache/"
cleanup-interval = "30m"
files-total-size-soft-limit = "1Gi"
