name: Run example

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590
      - run: nix-shell --run './run.sh'
  benchmark:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: true
      - uses: cachix/install-nix-action@d64e0553100205688c0fb2fa16edb0fc8663c590
      - run: nix-shell --run 'cd benchmarks/ && ./run.sh'
